### PR TITLE
Fixed model download link

### PR DESCRIPTION
**Pull request by 7exe**
Changed the old download link to the new OpenAI one.

### CODE REVIEW

**Comment by bobbapro** [comment]
Pardon my ignorance (I'm more an enduser than programmer), but does this resolve this error that I began around 2021-02-12? 

I'm using a slightly modified version of [drfinkus's Google Colab training for 1558M](https://colab.research.google.com/drive/1QE4LVEYITjIkjXxosahHVZPsSHtYZy7x#scrollTo=H7LoMj4GA4n_). 

 Any help is appreciated.

---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-1-270dd2e6232a> in <module>()
     56              only_train_transformer_layers=False,
     57              optimizer='adafactor',
---> 58              overwrite=True)
     59 
     60 

5 frames
/usr/lib/python3.7/json/decoder.py in raw_decode(self, s, idx)
    353             obj, end = self.scan_once(s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end

**Comment by 7exe** [comment]
It could've been caused by faulty model files, try checking the model files (By default, they should be in "models/1558M/") if they include an XML error string.

**Comment by bobbapro** [comment]
I feel really dumb. That's exactly what's causing the issue. What would be the easiest work around for this? Is it possible to do a "git clone" with the change/pull request? Or should I just do a replace in the file before "gpt2.download_gpt2(model_name="1558M")"? Working through Google Colab means that it has to clone the files each time the script is run.

Thank you so much for your help!

**Comment by 7exe** [comment]
Glad I could help, You could change the link in the gpt_2.py file manually, but Id personally run git clone on the pull request, https://github.com/7exe/gpt-2-simple

**Comment by drfinkus** [comment]
Great, thanks for the PR!

**Pull request merged**
